version: "3.7"

volumes:
    db_data:

services:
    recommended_products:
        build: .
        # image: jtirelli/recommended_products
        container_name: recommended_products
        environment:
            NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
            PGDATABASE: ${PGDATABASE}
            PGHOST: ${PGHOST}
            PGUSER: ${PGUSER}
            PGPASSWORD: ${PGPASSWORD}
            PGPORT: ${PGPORT}
        hostname: recommended_products
        ports:
            - 3003:3003
        restart: always